export const COLORS = {
  BLACK: "\u001b[30m",
  RED: "\u001b[31m",
  GREEN: "\u001b[32m",
  YELLOW: "\u001b[33m",
  BLUE: "\u001b[34m",
  MAGENTA: "\u001b[35m",
  CYAN: "\u001b[36m",
  WHITE: "\u001b[37m",
  BRIGHT_BLACK: "\u001b[30;1m",
  BRIGHT_RED: "\u001b[31;1m",
  BRIGHT_GREEN: "\u001b[32;1m",
  BRIGHT_YELLOW: "\u001b[33;1m",
  BRIGHT_BLUE: "\u001b[34;1m",
  BRIGHT_MAGENTA: "\u001b[35;1m",
  BRIGHT_CYAN: "\u001b[36;1m",
  BRIGHT_WHITE: "\u001b[37;1m",
  RESET: "\u001b[0m"
}

export const COLOR_BLACK = COLORS.BLACK;
export const COLOR_RED = COLORS.RED;
export const COLOR_GREEN = COLORS.GREEN;
export const COLOR_YELLOW = COLORS.YELLOW;
export const COLOR_BLUE = COLORS.BLUE;
export const COLOR_MAGENTA = COLORS.MAGENTA;
export const COLOR_CYAN = COLORS.CYAN;
export const COLOR_WHITE = COLORS.WHITE;
export const COLOR_BRIGHT_BLACK = COLORS.BRIGHT_BLACK;
export const COLOR_BRIGHT_RED = COLORS.BRIGHT_RED;
export const COLOR_BRIGHT_GREEN = COLORS.BRIGHT_GREEN;
export const COLOR_BRIGHT_YELLOW = COLORS.BRIGHT_YELLOW;
export const COLOR_BRIGHT_BLUE = COLORS.BRIGHT_BLUE;
export const COLOR_BRIGHT_MAGENTA = COLORS.BRIGHT_MAGENTA;
export const COLOR_BRIGHT_CYAN = COLORS.BRIGHT_CYAN;
export const COLOR_BRIGHT_WHITE = COLORS.BRIGHT_WHITE;
export const COLOR_RESET = COLORS.RESET;
